# Generated by Django 5.1.5 on 2025-01-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_salary_customuser_club_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='age',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='club',
            new_name='salary',
        ),
    ]
