# Generated by Django 5.1.4 on 2025-01-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='price',
            field=models.IntegerField(default=300, null=True, verbose_name='Укажите цену'),
        ),
    ]
