# Generated by Django 5.1.4 on 2025-01-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastags', '0002_genre_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='tags',
            field=models.ManyToManyField(to='hastags.tag'),
        ),
    ]
