# Generated by Django 5.1.5 on 2025-01-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_litres', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rezka',
            new_name='Linet',
        ),
    ]
