# Generated by Django 5.1.4 on 2025-01-17 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0003_alter_reviews_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('status', models.CharField(choices=[('In Cart', 'In Cart'), ('Purchased', 'Purchased'), ('Removed', 'Removed')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('related_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.books')),
            ],
        ),
    ]
