# Generated by Django 5.1.4 on 2025-01-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corzina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='item',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='shipping_address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
